name: Install libstdc++ headers

on: [push]

jobs:
  install-headers:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: Install dependencies
        run: pacman --noconfirm -Syu && pacman --needed --noconfirm -S base-devel git autoconf automake wget

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Git config
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Build toolchain
        run: |
          set -ex
          wget https://gist.github.com/mintsuki/233faa49819aa91d7d2f8502ceaa94fe/raw/27565ee6baf7fa03105bab3fe6c3e50efa022558/make_toolchain.sh
          chmod +x ./make_toolchain.sh
          TARGET="x86_64-elf" ./make_toolchain.sh

      - name: Move headers
        run: |
          set -ex
          mv ./include/features.h ./
          rm -rf include && mv toolchain/include/c++/* include
          mv ./features.h ./include/

      - name: Push
        run: |
          set -ex
          git config user.name 'mintsuki'
          git config user.email 'mintsuki@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/osdev0/libstdcxx-headers.git
          git fetch --all
          git add include
          git commit -m "Upload headers [ci skip]"
          git push origin master
