name: Build and install GCC headers

on: [push]

jobs:
  install-headers:
    strategy:
      matrix:
        target_arch: [i686, x86_64, aarch64, loongarch64, riscv64]

    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: Install dependencies
        run: pacman --noconfirm -Syu && pacman --needed --noconfirm -S base-devel git autoconf automake wget

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Git config
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Build toolchain
        run: |
          set -ex
          wget https://gist.github.com/mintsuki/0fa16d24ffec7cd473ab7da4a4eec1dc/raw/15259713aeb71efdb952f1de4016a66f26bdf6da/make_toolchain.sh
          chmod +x ./make_toolchain.sh
          TARGET="${{matrix.target_arch}}-elf" ./make_toolchain.sh

      - name: Move headers
        run: |
          set -ex
          mv ./x86_64/include/features.h ./
          mkdir -p ${{matrix.target_arch}}
          rm -rf ${{matrix.target_arch}}/include
          mv toolchain/include/c++/* ${{matrix.target_arch}}/include
          mv toolchain/lib/gcc/${{matrix.target_arch}}-elf/*/include/* ${{matrix.target_arch}}/include/
          mv ./features.h ./${{matrix.target_arch}}/include/

      - name: Push
        run: |
          set -ex
          git config user.name 'mintsuki'
          git config user.email 'mintsuki@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/osdev0/libstdcxx-headers.git
          while true; do \
            git pull --all; \
            git add ${{matrix.target_arch}}; \
            git commit -m "Upload headers (${{matrix.target_arch}}) [ci skip]"; \
            if git push origin master; then \
              break; \
            else \
              git reset HEAD~1; \
            fi; \
          done
